### ISSUE TITLE
Ambientação do usuário

### ISSUE THREAD

**Issue by danielhmarinho** [RedeLab/SOMOS#7]
Criação das telas de tutorial para novos usuários registrados na plataforma.

**Comment by onest-work** [comment]
![missao aceita](https://user-images.githubusercontent.com/11432392/38816491-9636ff96-416c-11e8-83b2-416e0e8a924d.png)
![missao concluida](https://user-images.githubusercontent.com/11432392/38816493-96739b36-416c-11e8-819e-45ea8776665a.png)
![missao enviada para validacao](https://user-images.githubusercontent.com/11432392/38816494-96b3c274-416c-11e8-9e0b-a95b0e003afb.png)
![missao](https://user-images.githubusercontent.com/11432392/38816495-96f16db8-416c-11e8-9657-c5979ebfa100.png)
